---
- hosts: webservers
  become: true

  vars:
    packages:
      - vim
      - zip
      - curl
      - nginx

  tasks:

    - name: Install packages on RedHat
      when: ansible_os_family == "RedHat"
      yum:
        name: "{{ packages }}"
        state: present

    - name: Install packages on Debian
      when: ansible_os_family == "Debian"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
