apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
          # Define resource limits and requests for the container to ensure it has enough resources to run efficiently and to prevent it from consuming too many resources on the node. {Optional}
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      readinessProbe:
        httpGet:
          path: /
          port: 80